// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MyMessage.proto
// Protobuf Java Version: 4.34.0-rc1

package com.example.study.nettyself.protobuf2;

@com.google.protobuf.Generated
public final class MyMessagePOJO extends com.google.protobuf.GeneratedFile {
  private MyMessagePOJO() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      "MyMessagePOJO");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.Person person = 1;</code>
     * @return The person.
     */
    com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getPerson();
    /**
     * <code>.Person person = 1;</code>
     */
    com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>.Worker worker = 2;</code>
     * @return Whether the worker field is set.
     */
    boolean hasWorker();
    /**
     * <code>.Worker worker = 2;</code>
     * @return The worker.
     */
    com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getWorker();
    /**
     * <code>.Worker worker = 2;</code>
     */
    com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder getWorkerOrBuilder();

    /**
     * <code>.MyMessage.DataType data_type = 3;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.MyMessage.DataType data_type = 3;</code>
     * @return The dataType.
     */
    com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType getDataType();

    com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        "MyMessage");
    }
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code MyMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PersonType = 0;</code>
       */
      PersonType(0),
      /**
       * <code>WorkerType = 1;</code>
       */
      WorkerType(1),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 34,
          /* patch= */ 0,
          /* suffix= */ "-rc1",
          "DataType");
      }
      /**
       * <code>PersonType = 0;</code>
       */
      public static final int PersonType_VALUE = 0;
      /**
       * <code>WorkerType = 1;</code>
       */
      public static final int WorkerType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return PersonType;
          case 1: return WorkerType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValue(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.getDescriptor().getEnumType(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyMessage.DataType)
    }

    private int dataCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PERSON(1),
      WORKER(2),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return PERSON;
          case 2: return WORKER;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    /**
     * <code>.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return dataCase_ == 1;
    }
    /**
     * <code>.Person person = 1;</code>
     * @return The person.
     */
    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getPerson() {
      if (dataCase_ == 1) {
         return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_;
      }
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
    }
    /**
     * <code>.Person person = 1;</code>
     */
    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder getPersonOrBuilder() {
      if (dataCase_ == 1) {
         return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_;
      }
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
    }

    public static final int WORKER_FIELD_NUMBER = 2;
    /**
     * <code>.Worker worker = 2;</code>
     * @return Whether the worker field is set.
     */
    @java.lang.Override
    public boolean hasWorker() {
      return dataCase_ == 2;
    }
    /**
     * <code>.Worker worker = 2;</code>
     * @return The worker.
     */
    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getWorker() {
      if (dataCase_ == 2) {
         return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_;
      }
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
    }
    /**
     * <code>.Worker worker = 2;</code>
     */
    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder getWorkerOrBuilder() {
      if (dataCase_ == 2) {
         return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_;
      }
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 3;
    private int dataType_ = 0;
    /**
     * <code>.MyMessage.DataType data_type = 3;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.MyMessage.DataType data_type = 3;</code>
     * @return The dataType.
     */
    @java.lang.Override public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType getDataType() {
      com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType result = com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.forNumber(dataType_);
      return result == null ? com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeMessage(1, (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_);
      }
      if (dataType_ != com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.PersonType.getNumber()) {
        output.writeEnum(3, dataType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_);
      }
      if (dataType_ != com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.PersonType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, dataType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage)) {
        return super.equals(obj);
      }
      com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage other = (com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 2:
          if (!getWorker()
              .equals(other.getWorker())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 2:
          hash = (37 * hash) + WORKER_FIELD_NUMBER;
          hash = (53 * hash) + getWorker().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.Builder.class);
      }

      // Construct using com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (personBuilder_ != null) {
          personBuilder_.clear();
        }
        if (workerBuilder_ != null) {
          workerBuilder_.clear();
        }
        dataType_ = 0;
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage getDefaultInstanceForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage build() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage buildPartial() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage result = new com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dataType_ = dataType_;
        }
      }

      private void buildPartialOneofs(com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage result) {
        result.dataCase_ = dataCase_;
        result.data_ = this.data_;
        if (dataCase_ == 1 &&
            personBuilder_ != null) {
          result.data_ = personBuilder_.build();
        }
        if (dataCase_ == 2 &&
            workerBuilder_ != null) {
          result.data_ = workerBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage) {
          return mergeFrom((com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage other) {
        if (other == com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case WORKER: {
            mergeWorker(other.getWorker());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetPersonFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetWorkerFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataCase_ = 2;
                break;
              } // case 18
              case 24: {
                dataType_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Person, com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder> personBuilder_;
      /**
       * <code>.Person person = 1;</code>
       * @return Whether the person field is set.
       */
      @java.lang.Override
      public boolean hasPerson() {
        return dataCase_ == 1;
      }
      /**
       * <code>.Person person = 1;</code>
       * @return The person.
       */
      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getPerson() {
        if (personBuilder_ == null) {
          if (dataCase_ == 1) {
            return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_;
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
        } else {
          if (dataCase_ == 1) {
            return personBuilder_.getMessage();
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.Person person = 1;</code>
       */
      public Builder setPerson(com.example.study.nettyself.protobuf2.MyMessagePOJO.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.Person person = 1;</code>
       */
      public Builder setPerson(
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.Person person = 1;</code>
       */
      public Builder mergePerson(com.example.study.nettyself.protobuf2.MyMessagePOJO.Person value) {
        if (personBuilder_ == null) {
          if (dataCase_ == 1 &&
              data_ != com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance()) {
            data_ = com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.newBuilder((com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 1) {
            personBuilder_.mergeFrom(value);
          } else {
            personBuilder_.setMessage(value);
          }
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Person person = 1;</code>
       */
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder getPersonBuilder() {
        return internalGetPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.Person person = 1;</code>
       */
      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder getPersonOrBuilder() {
        if ((dataCase_ == 1) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 1) {
            return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_;
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Person, com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder> 
          internalGetPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(dataCase_ == 1)) {
            data_ = com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.study.nettyself.protobuf2.MyMessagePOJO.Person, com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder>(
                  (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 1;
        onChanged();
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker, com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder> workerBuilder_;
      /**
       * <code>.Worker worker = 2;</code>
       * @return Whether the worker field is set.
       */
      @java.lang.Override
      public boolean hasWorker() {
        return dataCase_ == 2;
      }
      /**
       * <code>.Worker worker = 2;</code>
       * @return The worker.
       */
      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getWorker() {
        if (workerBuilder_ == null) {
          if (dataCase_ == 2) {
            return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_;
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return workerBuilder_.getMessage();
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      public Builder setWorker(com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker value) {
        if (workerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          workerBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      public Builder setWorker(
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder builderForValue) {
        if (workerBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          workerBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      public Builder mergeWorker(com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker value) {
        if (workerBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance()) {
            data_ = com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.newBuilder((com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            workerBuilder_.mergeFrom(value);
          } else {
            workerBuilder_.setMessage(value);
          }
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      public Builder clearWorker() {
        if (workerBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          workerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder getWorkerBuilder() {
        return internalGetWorkerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder getWorkerOrBuilder() {
        if ((dataCase_ == 2) && (workerBuilder_ != null)) {
          return workerBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_;
          }
          return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker, com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder> 
          internalGetWorkerFieldBuilder() {
        if (workerBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
          }
          workerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker, com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder, com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder>(
                  (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();
        return workerBuilder_;
      }

      private int dataType_ = 0;
      /**
       * <code>.MyMessage.DataType data_type = 3;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.MyMessage.DataType data_type = 3;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.MyMessage.DataType data_type = 3;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType getDataType() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType result = com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.forNumber(dataType_);
        return result == null ? com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MyMessage.DataType data_type = 3;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage.DataType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000004;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MyMessage.DataType data_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage();
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        "Person");
    }
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_ = 0;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.Person)) {
        return super.equals(obj);
      }
      com.example.study.nettyself.protobuf2.MyMessagePOJO.Person other = (com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.study.nettyself.protobuf2.MyMessagePOJO.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.example.study.nettyself.protobuf2.MyMessagePOJO.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.Builder.class);
      }

      // Construct using com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getDefaultInstanceForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person build() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person buildPartial() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.Person result = new com.example.study.nettyself.protobuf2.MyMessagePOJO.Person(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.study.nettyself.protobuf2.MyMessagePOJO.Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.Person) {
          return mergeFrom((com.example.study.nettyself.protobuf2.MyMessagePOJO.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.study.nettyself.protobuf2.MyMessagePOJO.Person other) {
        if (other == com.example.study.nettyself.protobuf2.MyMessagePOJO.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.example.study.nettyself.protobuf2.MyMessagePOJO.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.study.nettyself.protobuf2.MyMessagePOJO.Person();
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorkerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Worker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Worker}
   */
  public static final class Worker extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Worker)
      WorkerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        "Worker");
    }
    // Use Worker.newBuilder() to construct.
    private Worker(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Worker() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_ = 0;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker)) {
        return super.equals(obj);
      }
      com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker other = (com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Worker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Worker)
        com.example.study.nettyself.protobuf2.MyMessagePOJO.WorkerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.class, com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.Builder.class);
      }

      // Construct using com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        age_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getDefaultInstanceForType() {
        return com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker build() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker buildPartial() {
        com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker result = new com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker) {
          return mergeFrom((com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker other) {
        if (other == com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Worker)
    }

    // @@protoc_insertion_point(class_scope:Worker)
    private static final com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker();
    }

    public static com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Worker>
        PARSER = new com.google.protobuf.AbstractParser<Worker>() {
      @java.lang.Override
      public Worker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Worker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Worker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.study.nettyself.protobuf2.MyMessagePOJO.Worker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Worker_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Worker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\"\235\001\n\tMyMessage\022\031\n\006perso" +
      "n\030\001 \001(\0132\007.PersonH\000\022\031\n\006worker\030\002 \001(\0132\007.Wor" +
      "kerH\000\022&\n\tdata_type\030\003 \001(\0162\023.MyMessage.Dat" +
      "aType\"*\n\010DataType\022\016\n\nPersonType\020\000\022\016\n\nWor" +
      "kerType\020\001B\006\n\004data\"\"\n\006Person\022\014\n\004name\030\001 \001(" +
      "\t\022\n\n\002id\030\002 \001(\005\"#\n\006Worker\022\014\n\004name\030\001 \001(\t\022\013\n" +
      "\003age\030\002 \001(\005B6\n%com.example.study.nettysel" +
      "f.protobuf2B\rMyMessagePOJOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MyMessage_descriptor,
        new java.lang.String[] { "Person", "Worker", "DataType", "Data", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_Worker_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Worker_descriptor,
        new java.lang.String[] { "Name", "Age", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
